### ISSUE TITLE
Update CSE Insight Enrichment Server doc

### ISSUE THREAD

**Issue by kimsauce** [SumoLogic/sumologic-documentation#1005]
The checksum file for the FedRAMP version of the Insight Enrichment Server shows up to version 1.0.3 - <https://script-collection.s3.amazonaws.com/caravel/checksum.txt>
• However, the download link in the documentation links directly to 1.0.1 - <https://help.sumologic.com/docs/cse/integrations/insight-enrichment-server/>
I was able to download 1.0.3 just fine by changing the download URL
• also on that page - JAVA_PATH should be JAVA_HOME
• also C:\Windows\SumoLogic\EnrichmentServer should be C:\Windows\SumoLogic\EnrichmentService
• and another Enrichment Server documentation issue - <https://help.sumologic.com/docs/cse/integrations/insight-enrichment-server/>
per the docs, when I set my _proxy_url_ variable to _<http://x.x.x.x>:xxxx_ (using an IP address, so x.x.x.x in my example), the only error I was seeing in enricher.log was: *[ERROR InsightManager:236] <http://x.x.x.x>*
no traffic was getting sent from the Enrichment Server to the proxy via the Insight Enrichment Server service. the issue? the _http://_

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1669036703423919)

**Comment by MariePMcGarry** [comment]
Fixed in https://github.com/SumoLogic/sumologic-documentation/pull/1095

**Comment by MariePMcGarry** [comment]
FIxed in https://github.com/SumoLogic/sumologic-documentation/pull/1095.

**Comment by ramneetm20** [comment]
The download still points to 1.0.1 for the FedRAMP version, despite 1.0.3 being listed in the checksums file at https://script-collection.s3.amazonaws.com/caravel/checksum.txt . now I'm wondering if 1.0.3 IS the latest FedRAMP version, or if there's a newer version with bug fixes that simply hasn't been linked to
<img width="672" alt="Screenshot 2023-02-24 at 8 00 03 PM" src="https://user-images.githubusercontent.com/106404087/221327263-46253a73-6f6f-42b7-9302-fe5fa1ebd2b0.png">

**Comment by kimsauce** [comment]
> The download still points to 1.0.1 for the FedRAMP version, despite 1.0.3 being listed in the checksums file at https://script-collection.s3.amazonaws.com/caravel/checksum.txt . <img alt="Screenshot 2023-02-24 at 8 00 03 PM" width="672" src="https://user-images.githubusercontent.com/106404087/221327263-46253a73-6f6f-42b7-9302-fe5fa1ebd2b0.png">

@ramneetm20 , thank you for letting us know. @ptobia @pkazmir-sumo , I'll reopen this ticket.
