### ISSUE TITLE
404 on https://help.sumologic.com/Send_Data/Sources/03Use_JSON_to_Configure_Sources/JSON_Parameters_for_Hosted_Sources

### ISSUE THREAD

**Issue by majormoses** [SumoLogic/sumologic-documentation#1020]
Dead documentation link from terraform provider

**Steps to reproduce the behavior:**
1. Go to https://help.sumologic.com/Send_Data/Sources/03Use_JSON_to_Configure_Sources/JSON_Parameters_for_Hosted_Sources
1. See 404 instead of expected content

**Expected behavior:**
Links should go to valid places.

**Comment by stacykor** [comment]
Only this isn't a standard link. 

There is a redirect for what is expected which is:

https://help.sumologic.com/**03Send-Data**/Sources/03Use-JSON-to-Configure-Sources/JSON-Parameters-for-Hosted-Sources.

I'm happy to add another re-direct but can you send me the link/screenshot on the terraform provider where this occurred? I

**Comment by stacykor** [comment]
https://github.com/SumoLogic/sumologic-documentation/pull/1035
