### ISSUE TITLE
Broken Link - HTTP Sources

### ISSUE THREAD

**Issue by kostuch-sumologic** [SumoLogic/sumologic-documentation#1028]
From the **Configure a Hosted Collector and Source** page (https://help.sumologic.com/docs/send-data/hosted-collectors/configure-hosted-collector/), the **HTTP Sources** link is broken. 

HTTP Sources is located at the bottom of the page.  
![Screen Shot 2022-11-23 at 1 42 43 PM](https://user-images.githubusercontent.com/106690344/203623978-2bacf176-df46-4171-9e02-225aa8f01fcd.png)

Clicking on HTTP Sources directs to https://users/kpohas/sumologic-documentation/docs/send-data/hosted-collectors/http-source.

**Comment by kimsauce** [comment]
fixed
