### ISSUE TITLE
link fix for CloudTrail Security Monitoring

### ISSUE THREAD

**Issue by MariePMcGarry** [SumoLogic/sumologic-documentation#1050]
Hi Team, when installing the CloudTrail Security Monitoring &amp; Analytics integration, upon clicking "Open Setup Doc" it forwards you to <https://help.sumologic.com/docs/integrations/cloud-security-monitoring-analytics/aws-cloudtrail-pci-compliance/>

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1669661764901799)

**Comment by nmohantyctr** [comment]
Corrected the link in PR: https://github.com/SumoLogic/sumologic-documentation/pull/1138
