### ISSUE TITLE
Google Workspace AlertCenter UI/Docs fix

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#1062]
This note on [Google Workspace AlertCenter](https://help.sumologic.com/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-workspace-alertcenter) is very confusing - what "scope" needs to be added to the service account? There is no word of explanation about that earlier in the doc.
<img width="949" alt="image" src="https://user-images.githubusercontent.com/56411016/213561608-9b4e2c11-e416-4d39-9598-b2c2c94a524c.png">

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1669732086655809)

**Comment by MariePMcGarry** [comment]
@duchatran Can you help me resolve questions about [Google Workspace AlertCenter](https://help.sumologic.com/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-workspace-alertcenter/#step-1-create-service-account-credentials)?  

The complaint is valid. Topic says "If you don't add the scope to the service account you won't be authorized to fetch alert details." but we don't provide an explanation of what that means or how to do it.

I found this doc: [C2C: Google Workspace Alert Center](https://docs.google.com/document/d/12UKPyNHSKMdo6CdyakFcy-dPXKhpqZ8zRTa3kPpxMNw/edit#), which I don't recall seeing before.  

It seems like there is some info that I should take from that doc and add to the help topic. Could you review and give me some guidance?  Thanks very much.

**Comment by duchatran** [comment]
That is correct Marie. I see a reference to Google side and we should include that link as well

**Comment by MariePMcGarry** [comment]
@duchatran I was hoping you would be more specific about which sections of [C2C: Google Workspace Alert Center](https://docs.google.com/document/d/12UKPyNHSKMdo6CdyakFcy-dPXKhpqZ8zRTa3kPpxMNw/edit#), need added to [Google Workspace AlertCenter](https://help.sumologic.com/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-workspace-alertcenter/#step-1-create-service-account-credentials)?

**Comment by kimsauce** [comment]
Hi @duchatran , following up on this. I've taken a stab at updating. Can you please review [here](https://github.com/SumoLogic/sumologic-documentation/pull/1361)?

**Comment by kimsauce** [comment]
Update: UI in docs doesn't match product. @duchatran working with CON to investigate. Closing this Issue and we'll create a new PR once he gets back to us.
