### ISSUE TITLE
Incorrect CID redirects

### ISSUE THREAD

**Issue by JainM6** [SumoLogic/sumologic-documentation#1063]
Hi Team,

The doc link for the *Amazon CloudTrail - Cloud Security Monitoring and Analytics*  in the App Catalog is confusing as it navigates us to <https://help.sumologic.com/docs/integrations/cloud-security-monitoring-analytics/aws-cloudtrail-pci-compliance/>.
Also, The setup doc link for *CIS AWS Foundations Benchmark* is incorrect.  It takes us to _Share a Dashboard Outside Your Org_ <https://help.sumologic.com/docs/dashboards/share-dashboard-outside-org/>
cc: <@U8WP8747J>

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1669735863125109)

**Comment by rplahn** [comment]
You beat me to it @JainM6
I have a whole page of notes on this topic related to Cloud Trail in general. There are several docs that need to be updated as a group to help this all make sense. Very confusing ATM.  Happy to help with sharing info and suggesting edits, perhaps a quick internal call to level set is a good starting point.

**Comment by kimsauce** [comment]
> You beat me to it @JainM6 I have a whole page of notes on this topic related to Cloud Trail in general. There are several docs that need to be updated as a group to help this all make sense. Very confusing ATM. Happy to help with sharing info and suggesting edits, perhaps a quick internal call to level set is a good starting point.

Hi @rplahn , thank you so much for reaching out! We would love the help. @nmohantyctr manages the App Catalog docs and would be your contact for Cloudtrail edits. Maybe you two can connect over Slack?
