### ISSUE TITLE
Add metrics cheat sheet link

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#1081]
can this be added to our docs like we have done for logs cheat sheets? :slightly_smiling_face:  <https://support.sumologic.com/hc/en-us/community/posts/360003932694-Metrics-Operators-Cheat-Sheet>

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1669868966606869)

**Comment by MariePMcGarry** [comment]
Fixed in https://github.com/SumoLogic/sumologic-documentation/pull/1095
