### ISSUE TITLE
Enable download for OpenAPI 3 spec for Collector Management API

### ISSUE THREAD

**Issue by jeffreyaven** [SumoLogic/sumologic-documentation#1097]
**Is your feature request related to a problem? Please describe.**
No problem, just a feature request

**Describe the solution you'd like:**
I cannot find an OpenAPI spec for the Collector Management API, however you make other such API docs available such as [sumologic-api.yaml](https://api.sumologic.com/docs/sumologic-api.yaml).  We are building some tooling using the API and having access to the Collector API spec would be helpful (without having to reverse engineer operations and response schemas from the web docs).  

**Describe alternatives you have considered:**
Reverse engineering....  

**Additional info:**
None

**Comment by kimsauce** [comment]
Hi @jeffreyaven , many thanks for your inquiry. I believe this is something in the works. I've reached out to our API team to confirm and also find out if maybe there's a better workaround in the meantime.

**Comment by jeffreyaven** [comment]
> Hi @jeffreyaven , many thanks for your inquiry. I believe this is something in the works. I've reached out to our API team to confirm and also find out if maybe there's a better workaround in the meantime.

Thanks @kimsauce I've started reverse engineering this, would be happy to collaborate, I could explain what we are doing and get your thoughts

**Comment by jeffreyaven** [comment]
@kimsauce see attached, I have generated and tested this spec, would be great to get your feedback
[collectors.zip](https://github.com/SumoLogic/sumologic-documentation/files/10190470/collectors.zip)

**Comment by kimsauce** [comment]
Hi @jeffreyaven, apologies for the delay. It took me a few days trying to find the right contact person for this project. I'm going to send an email to the address listed in your profile.

This sounds like it will be helpful to the engineering teams - thank you so much again! Talk soon.

**Comment by kimsauce** [comment]
Closing out this ticket -- convo moved over to email.
