### ISSUE TITLE
Broken link - AWS Inspector app

### ISSUE THREAD

**Issue by MariePMcGarry** [SumoLogic/sumologic-documentation#1103]
On https://help.sumologic.com/docs/integrations/amazon-aws/inspector/ there is a link in the "Collecting Findings for the Amazon Inspector App" section to Step 2 that's broken. 

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1670359386724369?thread_ts=1670359363.287659&cid=C0S86TM6K)

**Comment by nmohantyctr** [comment]
Corrected link in PR: https://github.com/SumoLogic/sumologic-documentation/pull/1175
