### ISSUE TITLE
Broken anchor link - Metrics doc

### ISSUE THREAD

**Issue by kimsauce** [SumoLogic/sumologic-documentation#1111]
https://help.sumologic.com/docs/manage/ingestion-volume/monitor-ingestion-receive-alerts

<img width="565" alt="Screen Shot 2022-12-06 at 10 50 19 PM" src="https://user-images.githubusercontent.com/56411016/206108812-a0243faf-a604-448e-897d-9400cf6c6b0c.png">

**Comment by MariePMcGarry** [comment]
Fixed in source.
