### ISSUE TITLE
Amazon SNS updates

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#1159]
Hey Team.  On the page within the comments section of this post, we talk about capturing AWS Configs via SNS Topic.  There is a section that states:  Enable SNS Notification in AWS Config.  There has been some updates to AWS so these steps are off a bit.  Please see my detailed writeup in the comments sections along with the URL.

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1670946164427529?thread_ts=1670946164.427529&cid=C0S86TM6K)

**Comment by nmohantyctr** [comment]
Will work with the apps team under: https://jira.kumoroku.com/jira/browse/SUMO-208881
