### ISSUE TITLE
error in source name

### ISSUE THREAD

**Issue by MariePMcGarry** [SumoLogic/sumologic-documentation#1161]
<https://help.sumologic.com/docs/integrations/saas-cloud/gmail-tracelogs/>
and
<https://help.sumologic.com/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/gmail-tracelogs-source/>

mentions source App + source as `Gmail TraceLogs`

BUT actual name is

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1670952615746639)

**Comment by nmohantyctr** [comment]
Doc updated under PR: https://github.com/SumoLogic/sumologic-documentation/pull/1252
