### ISSUE TITLE
OT collection

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#1162]
In our Open Telemetry Help article, it seems to give the impression that only traces are supported…?

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1670953870115569)

**Comment by kimsauce** [comment]
[OTEL doc](https://help.sumologic.com/docs/send-data/sumo-distribution-opentelemetry/) 2nd sentence: _It provides a single unified agent to send Logs, Metrics, Traces, and Metadata for Observability to Sumo Logic._

Have reached out to requester 3x to clarify if they were referring to a different doc.
