### ISSUE TITLE
Broken link in release notes

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#1165]
Hello Doc, this page <https://help.sumologic.com/release-notes-collector/2022/07/20/> has a broken link, it says on this line:
```Collector running as non-root user. Collector running as non-root user ( run as mode) cannot be upgraded through the API/Web UI. It will run and give an error message that the upgrade is not possible. It needs to be upgraded manually on your machine. Steps to manually upgrade.```
In the part where it says “Steps to manually upgrade.” I think that is meant to be a link to take you to this page <https://help.sumologic.com/docs/send-data/collection/upgrade-collectors/#upgrade-collectors-using-the-command-line>.

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1670983054518619)

**Comment by stacykor** [comment]
PR-1168

**Comment by kimsauce** [comment]
fixed in PR #1168
