### ISSUE TITLE
Remove cloud-sensor-guide

### ISSUE THREAD

**Issue by JainM6** [SumoLogic/sumologic-documentation#1173]
I’m pretty sure this page should be removed.
<https://help.sumologic.com/docs/cse/sensors/cloud-sensor-guide/>

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1671022299485149?thread_ts=1671022299.485149&cid=C0S86TM6K)

**Comment by MariePMcGarry** [comment]
@JainM6 I've reached out to PM to make sure it's fine to remove this page now. I'll take care it once I get confirmation.

**Comment by JainM6** [comment]
@MariePMcGarry Thank you so much, Marie. I will change the assignee's name.

**Comment by MariePMcGarry** [comment]
removed cloud sensor page, https://github.com/SumoLogic/sumologic-documentation/pull/1184
