### ISSUE TITLE
link issue in search results

### ISSUE THREAD

**Issue by MariePMcGarry** [SumoLogic/sumologic-documentation#1181]
<@U4HKQNM2Q>, I am trying to find aws cost explorer docs. When using the search, I type in “explorer”  and the first link doesn’t work, but then the bottom link works (see attachment).

First link’s url: <https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-cost-explorer?ss360SearchTerm=explorer>
Second link’s url: <https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-cost-explorer-source/>

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1671040497005989)

**Comment by kimsauce** [comment]
fixed in ss360
