### ISSUE TITLE
No write access

### ISSUE THREAD

**Issue by kbidus-sumologic** [SumoLogic/sumologic-documentation#1186]
Hi, I wanted to propose a change to some docs by creating a PR with the proposed change but I don't have write access to this repo.

```git push --set-upstream origin kbidus/tracing/http-source
remote: Permission to SumoLogic/sumologic-documentation.git denied to kbidus-sumologic.
fatal: unable to access 'https://github.com/SumoLogic/sumologic-documentation.git/': The requested URL returned error: 403

**Comment by kimsauce** [comment]
Hi @kbidus-sumologic , thanks for reaching out. You can either:
* Fork the repo (instructions [here](https://help.sumologic.com/docs/contributing/#fork-and-clone-the-sumo-docs-repository)) and you'll be prompted to sign a CLA, granting you write access
* Follow our internal [Getting Started](https://docs.google.com/document/d/1eR9bwMpvbMJX6slJ5795SA6zOAbD1SvcT3zJJDDG1WI/edit?usp=sharing) guide

If you have any more Qs, please reach out to #dochub on Slack.
