### ISSUE TITLE
Monitors - clarify share option

### ISSUE THREAD

**Issue by kimsauce** [SumoLogic/sumologic-documentation#1206]
We do not have a share option for monitors. Monitors stop executing when the creator is deleted. In that case, you need to duplicate the monitor under another user.

The https://help.sumologic.com/docs/alerts/monitors/monitor-faq/#one-of-our-monitors-suddenly-stopped-sending-notifications-even-though-i-see-it-on-the-monitors-page and https://help.sumologic.com/docs/manage/users-roles/users/delete-user/#what-happens-when-you-delete-a-user page mentions this.  

we should update the monitors documentation to include a heads up about this.

[Slack Message](https://sumologic.slack.com/archives/CT8EX5VHB/p1671581986064049?thread_ts=1671156591.598459&cid=CT8EX5VHB)

**Comment by stacykor** [comment]
@Melvin-CnC please write a note for the  https://help.sumologic.com/docs/alerts/monitors/#limitations page 
"Note: You cannot share monitors, you must duplicate the monitor under another user" and get @angadrandhawa1 to review.

**Comment by Melvin-CnC** [comment]
@stacykor added and later edited the note.

**Comment by kimsauce** [comment]
Hi @stacykor @Melvin-CnC , this was not exactly the edit suggested by SMEs and requires further discussion. The Slack thread above is quite lengthy with a lot of back and forth. Happy to share it with you over email so that you can reach out to the involved parties (Support staff and Monitors team). For now, I'm going to [revert the edit](https://github.com/SumoLogic/sumologic-documentation/pull/1499).

**Comment by jpipkin1** [comment]
Pull request: https://github.com/SumoLogic/sumologic-documentation/pull/4797

**Comment by jpipkin1** [comment]
The article is updated: https://help.sumologic.com/docs/alerts/monitors/settings/#more-actions
