### ISSUE TITLE
Log Monitors behavior fix

### ISSUE THREAD

**Issue by kimsauce** [SumoLogic/sumologic-documentation#1211]
Current behavior for log monitors:
• Missing data group alerts auto-resolve (via expiry) after 7 days.
• Critical and warning ones also auto-resolve after 7 days of missing data.
Current behavior for metrics monitors:
• Missing data alerts auto-resolve (via expiry) after 1 day.
• Critical and warning ones auto-resolve after "query time range" + some delta. So if query time range is 15 mins, it can be anywhere between 15 to 20 mins depending on the scenario.
My recommendation:
• Logs missing data alerts should auto-resolve after 1 day (via expiry) - same as metrics ones: needs code changes.
• Logs critical and warning continue to remain in triggered state as long as alert condition continues to match. 
• We should document the current behavior. cc <@UK8GRBSQZ> to verify logs one and <@UMYT715GR> for metrics one. Since this is a little complex, please provide the exact content.

[Slack Message](https://sumologic.slack.com/archives/CTG4GRVNY/p1671608043529799?thread_ts=1671095427.864489&cid=CTG4GRVNY)

**Comment by jpipkin1** [comment]
Related ticket: https://sumologic.atlassian.net/browse/SUMO-208482

**Comment by jpipkin1** [comment]
@kimsauce, I'm closing this issue because you resolved it with [SUMO-208482](https://sumologic.atlassian.net/browse/SUMO-208482).
