### ISSUE TITLE
Docs link on Learn tab

### ISSUE THREAD

**Issue by MariePMcGarry** [SumoLogic/sumologic-documentation#1265]
On the Learn tab, if you click the "docs" link it goes to a page not found and then to : <http://help.sumologic.com/?cid=-1|help.sumologic.com/?cid=-1>. and it should just go to "<https://help.sumologic.com/>". Can we double check the mapping file and make sure that old link points to the <http://help.sumologic.com|help.sumologic.com> site?

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1672858148905789?thread_ts=1672858148.905789&cid=C0S86TM6K)

**Comment by kimsauce** [comment]
This error is coming from the product side, not docs. Have reached out to product UX team.
