### ISSUE TITLE
Broken reset password link

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#1314]
Help docs link from reset password email is broken
<https://help.sumologic.com/01Start-Here/02Getting-Started/01-How-to-Sign-Up-for-Sumo-Logic>

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1673518150632999)

**Comment by kimsauce** [comment]
fixed with:
https://github.com/SumoLogic/sumologic-documentation/pull/1315
https://github.com/SumoLogic/sumologic-documentation/pull/1316
