### ISSUE TITLE
Microsoft Teams - fix missing screenshots

### ISSUE THREAD

**Issue by kimsauce** [SumoLogic/sumologic-documentation#1317]
Screenshot of the dashboards on this page are not visible. At least 6 screenshots are missing here https://help.sumologic.com/docs/integrations/microsoft-azure/teams/

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1673555892131199)

**Comment by nmohantyctr** [comment]
Updated under: https://github.com/SumoLogic/sumologic-documentation/pull/1328
