### ISSUE TITLE
Webhook docs 404

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#1346]
Hey Team, I tried to access our webhook connections docs in our dochuband every single link 404's - example: <https://help.sumologic.com/docs/manage/connections-integrations/webhook-connections/set-up-webhook-connections/>

Ive used the sumo search bar in the doc hub and also google search and get the same results which makes me think these pages dont exist anymore

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1673647376437599)

**Comment by kimsauce** [comment]
resolved (see slack convo)
