### ISSUE TITLE
AWS Observability index page

### ISSUE THREAD

**Issue by kimsauce** [SumoLogic/sumologic-documentation#1360]
Sharing feedback directly from our customer:

Regarding the Sumo Logic documentation, there are things that could be improved. For instance... after [reading the docs](https://help.sumologic.com/docs/observability/aws/) a few times, I'm still not sure what "AWS Observability" means vs. just using the logs and metrics collected using the collector.

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1666960876273379)

**Comment by stacykor** [comment]
@nmohantyctr please work with Arun and Pawel to get the "infrastructure monitoring and application observability for apps running on the AWS infrastructure" these may be more familiar terms we can use to explain AWS Observability

**Comment by nmohantyctr** [comment]
Created JIRA: https://jira.kumoroku.com/jira/browse/SUMO-212204 for this issue. Hence closing the issue.
