### ISSUE TITLE
VMWare doc missing image

### ISSUE THREAD

**Issue by kimsauce** [SumoLogic/sumologic-documentation#1381]
https://help.sumologic.com/docs/integrations/containers-orchestration/vmware. .. Just above the header _Sample log message_, it says "The following image illustrates the collection process." however, there is no image. Can you load the image?

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1673931293873619?thread_ts=1673931293.873619&cid=C0S86TM6K)

**Comment by stacykor** [comment]
@nmohantyctr will look at this one.

**Comment by kimsauce** [comment]
resolved
