### ISSUE TITLE
New Help Topic -- Global Confidence

### ISSUE THREAD

**Issue by kostuch-sumologic** [SumoLogic/sumologic-documentation#1383]
**Is your feature request related to a problem? Please describe.**
Global Confidence is not a searchable term in the help documentation.  Global Confidence is explained on the Global Intelligence for Security Insights page.  In CSE, the term Global Confidence is used.  

**Describe the solution you'd like:**
Have "global confidence" as a search term that directs to this page -- https://help.sumologic.com/docs/cse/records-signals-entities-insights/global-intelligence-security-insights/.  

**Describe alternatives you have considered:**
n/a

**Additional info:**
n/a

**Comment by kimsauce** [comment]
All set, @kostuch-sumologic . Thank you for letting us know! I've pinned some additional related docs after the one you called out.
<img width="675" alt="Screenshot 2023-01-17 at 2 39 52 PM" src="https://user-images.githubusercontent.com/56411016/213028119-d1a96b0d-e3c4-40d4-81e5-fcf8a35fc0dd.png">
