### ISSUE TITLE
Metrics operator redirects broken

### ISSUE THREAD

**Issue by kimsauce** [SumoLogic/sumologic-documentation#1402]
Hi, currently we use old links to metrics operators which are redirected to new URL-s.
<https://sumologic.slack.com/archives/C0S86TM6K/p1664779623166569|Link to the previous discussion>
We're enabling a link to <https://help.sumologic.com/docs/metrics/metrics-operators/predict/|predict operator documentation>. Can I ask for a new redirect for it, or should we maybe change the old operator documentation URL-s in the code to new ones?

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1674121558665739)

**Comment by MariePMcGarry** [comment]
CID for predict topic is _19800_. I'm working with @msbatura on what other CIDs he needs.
