### ISSUE TITLE
Clarify alerts for when data is not sent

### ISSUE THREAD

**Issue by kimsauce** [SumoLogic/sumologic-documentation#1404]
Clarify best practice for being alerted when data is not sent. I know we have this documentation which is for scheduled searches. Would Monitors be a better fit now? 

https://help.sumologic.com/docs/manage/ingestion-volume/monitor-ingestion-receive-alerts/#data-not-sent-alert

Created from Slack: https://sumologic.slack.com/archives/CT8EX5VHB/p1661963152352939?thread_ts=1661963152.352939&cid=CT8EX5VHB

**Comment by kimsauce** [comment]
@angadrandhawa1 @tarunk2 , would you be able to help me with this? My understanding is we'd need to [revise this section](https://help.sumologic.com/docs/manage/ingestion-volume/monitor-ingestion-receive-alerts/#scheduling-3) to recommend setting up Monitor ingestion lag?

**Comment by stacykor** [comment]
SMEs need to clarify. Not a good fit for Melvin

**Comment by kimsauce** [comment]
fixed https://help.sumologic.com/docs/manage/ingestion-volume/monitor-ingestion-receive-alerts/
