### ISSUE TITLE
Port number for HTTP POST v2 of CSE Action

### ISSUE THREAD

**Issue by tetsuro2** [SumoLogic/sumologic-documentation#1443]
**Provide Feedback on Docs**
I heard that only certain ports can be used as the destination for HTTP POST v2 of CSE Action. 
Please write in help which ports can be used by CSE Action

https://help.sumologic.com/docs/cse/administration/create-cse-actions/#http-post-v2

**Comment by stacykor** [comment]
Marie will look at it. Will not assign to Melvin.

**Comment by MariePMcGarry** [comment]
Thanks @tetsuro2!

I've submitted https://github.com/SumoLogic/sumologic-documentation/pull/1477 to update https://help.sumologic.com/docs/cse/administration/create-cse-actions/#http-post-v2.
