### ISSUE TITLE
Built-in metadata fields

### ISSUE THREAD

**Issue by kimsauce** [SumoLogic/sumologic-documentation#1456]
The fields we are worried about the using are listed here https://help.sumologic.com/docs/search/get-started-with-search/search-basics/built-in-metadata/ . A further complication is these fields have a short hand name. In this example "_sourceName" can also be refered to with "Name". We probably need to improve the documentation on the built-in-metadata page to include these shorthand names as well

_Originally posted by @dstephens5 in https://github.com/SumoLogic/sumologic-documentation/pull/1286#discussion_r1072848194_

**Comment by stacykor** [comment]
This one still needs to be resolved by SMEs. Will not assign to Melvin for now.
