### ISSUE TITLE
Two PCI Compliance for AWS CloudTrail app docs?

### ISSUE THREAD

**Issue by kimsauce** [SumoLogic/sumologic-documentation#1514]
I see two docs for PCI Compliance for AWS CloudTrail App. Information looks different, but it's confusing because there's only one such app in the App Catalog. @nmohantyctr , can you investigate?

https://help.sumologic.com/docs/integrations/cloud-security-monitoring-analytics/aws-cloudtrail-pci-compliance

https://help.sumologic.com/docs/integrations/amazon-aws/cloudtrail-pci-compliance

**Comment by jpipkin1** [comment]
I'm closing this ticket because this article no longer exists:
https://help.sumologic.com/docs/integrations/cloud-security-monitoring-analytics/aws-cloudtrail-pci-compliance
