### ISSUE TITLE
Old release note link is broken on What's new page.

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#1532]
Hi Dochub crew, on our What's New Page (<https://www.sumologic.com/whats-new/>) there's a link to Alert Subscriptions that generates a 404.

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1675205253377729?thread_ts=1675205253.377729&cid=C0S86TM6K)

**Comment by stacykor** [comment]
PR 1533

**Comment by kimsauce** [comment]
Fixed per Slack thread, and all legacy redirects now in place to support legacy What's New posts
