### ISSUE TITLE
Minor typo where "from" is repeated

### ISSUE THREAD

**Issue by saagarwal-sumo** [SumoLogic/sumologic-documentation#1536]
Description
The word "from" is repeated on this page https://help.sumologic.com/docs/metrics/introduction/joins/#why-use-along
i.e.
"You can combine (join) the results of multiple queries, or use values from one query to filter values from from another."

**Steps to reproduce the behavior:**
1. Go to https://help.sumologic.com/docs/metrics/introduction/joins/#why-use-along
2. Check the below line
"You can combine (join) the results of multiple queries, or use values from one query to filter values from from another."

**Expected behavior:**
The word "from" should come only once

**Comment by MariePMcGarry** [comment]
Thanks, @saagarwal-sumo. I fixed the typo in https://github.com/SumoLogic/sumologic-documentation/pull/1566.
