### ISSUE TITLE
Search keyword subdomain

### ISSUE THREAD

**Issue by kostuch-sumologic** [SumoLogic/sumologic-documentation#1545]
**Describe the bug:**
Searching for "subdomain" does not retrieve desired page.  

**Expected behavior:**
Please link "subdomain" to the Manage Organizational Settings page.  

https://help.sumologic.com/docs/manage/manage-subscription/manage-org-settings/#set-up-a-customsubdomain

**Comment by MariePMcGarry** [comment]
@kostuch-sumologic I updated tags and keywords for that doc page in https://github.com/SumoLogic/sumologic-documentation/pull/1566. Hopefully that will do the trick. Note also that soon we'll have a better search tool.

**Comment by kostuch-sumologic** [comment]
I searched for **subdomain** and the page does not display/is a result.
