### ISSUE TITLE
Normalized Severity operator typo

### ISSUE THREAD

**Issue by kostuch-sumologic** [SumoLogic/sumologic-documentation#1555]
**Describe the bug:**
Normalized Severity should be one word in the CSE signal generation syntax.  The screen captures under the Scheduling the Search steps are wrong; they show normalized severity as two words.  It is correct (one word) under Required fields.

Doc URL - 
https://help.sumologic.com/docs/alerts/scheduled-searches/generate-cse-signals/#scheduling-the-search

**Steps to reproduce the behavior:**
1. Go to Generate CSE Signals With a Scheduled Search (url above).
1. Scroll down to Scheduling the Search
Look for: Normalized Severity in step 1 & 2 screen caps

**Screenshots**
![Screenshot 2023-02-02 at 4 43 57 PM](https://user-images.githubusercontent.com/106690344/216456540-77edf696-d291-47c3-91c7-38a98d40ef95.png)

**Comment by MariePMcGarry** [comment]
Replaced the image with the typo, in https://github.com/SumoLogic/sumologic-documentation/pull/1566
