### ISSUE TITLE
Broken link to threat rules

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#1615]
hi, this page <https://help.sumologic.com/docs/cse/rules/normalized-threat-rules/> has a broken link to <https://github.com/jasklabs/content-catalog/blob/master/rules/threat_rules.csv|threat_rules.csv> which can be found here <https://help.sumologic.com/docs/cse/rules/normalized-threat-rules/#normalized-threat-rules-support-multiple-log-sources>

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1676460956367529)

**Comment by kimsauce** [comment]
Link isn't broken -- it's a link to a private repo. Have asked @ptobia @pkazmir-sumo to advise.

**Comment by kimsauce** [comment]
Paul has fixed here https://github.com/SumoLogic/sumologic-documentation/pull/1618
