### ISSUE TITLE
Out-dated comparison of CloudWatch vs EC2 host metrics collectors in AWSO Prerequisites

### ISSUE THREAD

**Issue by jgranger-sumo** [SumoLogic/sumologic-documentation#1628]
**Describe the bug:**
In the AWSO deployment [Prerequisites](https://help.sumologic.com/docs/observability/aws/deploy-use-aws-observability/before-you-deploy/#prerequisites) section of the doc site it states:

> Sumo Logic Collectors and Sources. _The AWS Observability Solution relies upon an Installed Collector with a Host Metrics Source on each of your AWS EC2 hosts. The solution relies upon host metrics collection rather than AWS CloudWatch EC2 metrics because AWS EC2 metrics from Cloudwatch have high latency and can increase the costs of your AWS account. Host metrics have the advantage of near-zero latency and more information at a lower cost._ Instructions are provided in Configure Host Metric Source below.

**Steps to reproduce the behavior:**
1. Go to https://help.sumologic.com/docs/observability/aws/deploy-use-aws-observability/before-you-deploy/#prerequisites

**Expected behavior:**
With the use of Kinesis Firehose to feed CloudWatch metrics, and the inclusion of dashboards for both CloudWatch EC2 metrics and EC2 host metrics, the statement about the preference to use EC2 host metrics over CloudWatch metrics is no longer valid and needs to be qualified or replaced.

**Screenshots**
None

**Desktop/Tablet/Smartphone (please complete the following information):**
N/A

**Additional info:**
None

**Comment by kimsauce** [comment]
@nmohantyctr , can you please look into this?

**Comment by jpipkin1** [comment]
Closing this ticket because the erroneous text no longer appears in the [Prerequisites](https://help.sumologic.com/docs/observability/aws/deploy-use-aws-observability/before-you-deploy/#prerequisites) section of the article.
