### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by JainM6** [SumoLogic/sumologic-documentation#1658]
<https://help.sumologic.com/docs/alerts/monitors/alert-response/>  The text refers to items K through M but these are not labelled on any of the accompanying graphics.

[Slack Message](https://sumologic.slack.com/archives/CT8EX5VHB/p1676306411043809?thread_ts=1676306411.043809&cid=CT8EX5VHB)

**Comment by kimsauce** [comment]
Closing this out; all labels have corresponding images
