### ISSUE TITLE
Problem with import from reuse folder

### ISSUE THREAD

**Issue by astefanski-sumo** [SumoLogic/sumologic-documentation#1687]
**Describe the bug:**
Here https://help.sumologic.com/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source/#restarting-your-source one can see 

import useBaseUrl from '@docusaurus/useBaseUrl'; 

I do not know how to fix it so reporting this as a bug. 

**Steps to reproduce the behavior:**
1. Go to ['doc'](https://help.sumologic.com/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source/#restarting-your-source)
1. See the excerpt which should be not visible: "import useBaseUrl from '@docusaurus/useBaseUrl';"

**Expected behavior:**
Line in question should be hidden/gone

**Screenshots**

**Desktop/Tablet/Smartphone (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version Version 109.0.5414.119 (Official Build) (x86_64)

**Comment by kimsauce** [comment]
fixed
