### ISSUE TITLE
ELB log parsing example is incomplete

### ISSUE THREAD

**Issue by kimsauce** [SumoLogic/sumologic-documentation#1740]
Our example of ELB log parsing here is incomplete. While this example works it is missing a lot of good fields. He said we used to have a longer parse string. Is that something we want to correct or are we just showing this as a potential example?

<https://help.sumologic.com/docs/manage/field-extractions/parse-elb-logs/>

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1677539689234679)

**Comment by jpipkin1** [comment]
Closing this issue because we couldn't get a good example. See [Slack thread](https://sumologic.slack.com/archives/C0S86TM6K/p1693339978535349?thread_ts=1677539689.234679&cid=C0S86TM6K).
