### ISSUE TITLE
default port number for syslog source

### ISSUE THREAD

**Issue by tetsuro2** [SumoLogic/sumologic-documentation#1813]
**Provide Feedback on Docs**
I think this is a typo.

**Specific page:**

https://help.sumologic.com/docs/send-data/installed-collectors/sources/syslog-source/#configure-a-syslog-source

**About the site:**

Port. Enter the port number for the Source to listen to. If the collector runs as root (default), use 51. Otherwise, consider 1514 or 5140. Make sure the devices are sending to the same port.

-> Should we recommend port 514 instead of port 51? Because Syslog default port is 514.
https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

**Comment by kimsauce** [comment]
@tetsuro2 you are correct - great catch! Fixing this now.
