### ISSUE TITLE
Missing Period - Threat Intel Quick Analysis

### ISSUE THREAD

**Issue by kostuch-sumologic** [SumoLogic/sumologic-documentation#1826]
**Describe the bug:**
Period missing (I think) on the Threat Intel Quick Analysis page. Under "Do IOCs and Threats expire?"

**Steps to reproduce the behavior:**
https://help.sumologic.com/docs/integrations/security-threat-detection/threat-intel-quick-analysis/#do-iocs-and-threats-expire

**Expected behavior:**
IOCs and Threats will often remain in the system because an IOC, such as an IP address, could go dormant and they reappear as part of another threat **missing period** The last valid one can be found under labels > Last_valid_on. Be aware that over the period, their Malicious Confidence can be downgraded or upgraded depending upon recent activity.

**Screenshots**
![Screenshot 2023-03-09 at 2 14 51 PM](https://user-images.githubusercontent.com/106690344/224130798-d372770d-7db9-42bf-b28d-3d20c5a442b1.png)

**Desktop/Tablet/Smartphone (please complete the following information):**

**Additional info:**

**Comment by kimsauce** [comment]
fixed here https://github.com/SumoLogic/sumologic-documentation/pull/1901
