### ISSUE TITLE
Update First Seen rule topic

### ISSUE THREAD

**Issue by ghost** [SumoLogic/sumologic-documentation#1862]
@eli-jang said in the #dochub channel:

"Hello Team,
Please update the screenshot and the description in the below page. The latest image attached."
<https://help.sumologic.com/docs/cse/rules/write-first-seen-rule/#example-rule>

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1678797456916939)
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/75449657/225075184-f9e9f0a4-d78c-45ec-80f7-7eb76295b099.png">

**Comment by jpipkin1** [comment]
Created the following branch to fix this issue:
https://github.com/SumoLogic/sumologic-documentation/tree/first-seen-rule-update

This branch adds the new image located here:
https://github.com/SumoLogic/sumologic-documentation/blob/first-seen-rule-update/static/img/cse/first-seen-rule-example-new.jpg

The new image is added to the "Example rule" section of this article:
https://github.com/SumoLogic/sumologic-documentation/edit/main/docs/cse/rules/write-first-seen-rule.md

**Comment by jpipkin1** [comment]
@eli-jang, you said "Please update the screenshot and the description in the below page." But after reviewing the text in the [Example rule](https://help.sumologic.com/docs/cse/rules/write-first-seen-rule/#example-rule) section, I don't think any of it needs to change based on the new screen image. 

Was there some specific text you wanted updated?
