### ISSUE TITLE
CSE APIs should be a table

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#1914]
The CSE APIs page here: https://help.sumologic.com/docs/cse/administration/cse-apis/

Should more closely match the APIs table with examples by deployment here for Sumo Logic:

https://help.sumologic.com/docs/api/getting-started/#sumo-logic-endpoints-by-deployment-and-firewall-security

**Comment by jpipkin1** [comment]
The issue is fixed by PR [1960](https://github.com/SumoLogic/sumologic-documentation/pull/1960) and [1961](https://github.com/SumoLogic/sumologic-documentation/pull/1961).
