### ISSUE TITLE
Lookup tables need additional docs

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#1984]
Request from @sakshi-sumo:

>We should add one more section [here](https://help.sumologic.com/docs/search/lookup-tables/) for mentioning how one can work with Lookup data. Yesterday I was trying but I didn't find any documentation that can help me in filtering out the lookup table data.

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1680078277797199)

**Comment by jpipkin1** [comment]
@sakshi-sumo, I'm sorry that we haven't addressed this ticket for more than a year!

To filter and search lookup table data, use search operators (see section "[Operators you use with Lookup Tables](https://help.sumologic.com/docs/search/lookup-tables/create-lookup-table/#operators-you-use-with-lookup-tables)"). 

To make it more clear, in pull request #4786 I'm changing the name of that section to "Find Lookup Tables content with search operators".

**Comment by jpipkin1** [comment]
The section is now updated:
https://help.sumologic.com/docs/search/lookup-tables/create-lookup-table/#find-lookup-tables-content-with-search-operators
