### ISSUE TITLE
Tracing Doc - Python Documentation Request

### ISSUE THREAD

**Issue by mauricio-lomeli-planview** [SumoLogic/sumologic-documentation#2117]
**Provide Feedback on Docs**
> The documentation doesn't seem finished. The variable `log` doesn't seem to exist in the current context. Where can I find additional Python documentation on how to use Summo Logic?

**Specific page:**
[Sumo Logic Python Documentation](https://help.sumologic.com/docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/python/traceid-spanid-injection-into-logs/)

**About the site:**
What would you like to see on the website?
> Would like a little more information with Python documentation.

**Comment by kimsauce** [comment]
@mauricio-lomeli-planview , many thanks for submitting this feedback. I'll get this to the Tracing Team and writer for review.

**Comment by mauricio-lomeli-planview** [comment]
I'm starting to like your team.

**Comment by kimsauce** [comment]
@mauricio-lomeli-planview were you able to check out the [main Python tracing documentation](https://help.sumologic.com/docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/python)? The doc you linked above was specific to traceID/spanID injection.
