### ISSUE TITLE
quantize documentation should show "to INTERVAL" as optional

### ISSUE THREAD

**Issue by MikeJansen** [SumoLogic/sumologic-documentation#2218]
I was looking for a way to modify just the rollup for `quantize`.  [The documentation](https://help.sumologic.com/docs/metrics/metrics-operators/quantize/) does not show that `to INTERVAL` is optional.

I created a question on [StackOverflow](https://stackoverflow.com/questions/76115405/sumo-logic-metric-query-override-quantize-rollup-but-leave-default-interval) and got an answer that you just leave `to INTERVAL` off.  I validated that this is the case.

The documentation should be updated to reflect that `to INTERVAL` is optional.

**Comment by kimsauce** [comment]
resolved with https://github.com/SumoLogic/sumologic-documentation/pull/2402
