### ISSUE TITLE
Feature Request Docs not accurate

### ISSUE THREAD

**Issue by bethg1** [SumoLogic/sumologic-documentation#2306]
**Is your feature request related to a problem? Please describe.**
The feature request docs are inaccurate. They say to " Go to Help > Feature Request to access the Ideas portal." But "Feature Request" is no longer an option under the help menu.
Ref: https://help.sumologic.com/docs/get-started/help/#feature-requests

**Describe the solution you'd like:**
The docs updated to reflect the new process for submitted a feature request. 

**Describe alternatives you have considered:**
A clear and concise description of any alternative solutions or features you have considered.
N/a

**Additional info:**
Doc that needs to be updated: https://help.sumologic.com/docs/get-started/help/#feature-requests
I found the feature request going to Help> Support> all the way at the bottom  Request a Feature

**Comment by kimsauce** [comment]
@bethg1 , many thanks for bringing this to our attention!
