### ISSUE TITLE
AWS ECS Fargate Container Logs JSON config not formatted correctly

### ISSUE THREAD

**Issue by bethg1** [SumoLogic/sumologic-documentation#2308]
**Describe the bug:**
Give a clear and concise description of the issue. Include any errors you received.

The sample config for the task definition for the ECS Fargate logs is not formatted correctly. The indentation is wrong, which then makes the service fail to start. 

**Steps to reproduce the behavior:**
1. Go to https://help.sumologic.com/docs/send-data/collect-from-other-data-sources/aws-fargate-log-collection/
2. Follow the steps to deploy the Task Definition 
**Specific step with the incorrectly formatted JSON:** You need to create a new task definition with a Log Router based on a FluentBit image and a container for your application using this [JSON](https://script-collection.s3.amazonaws.com/fargate/httpd_fargate_sumologic.json)].
3. Launch the service
4. Service fails to start, receive the following error:
`InternalError: unable to generate fireLens config file: unable to generate fireLens config content: unable to generate fluent config output section: unable to apply log options of container log_router_sumo to fireLens config: missing output key Name which is required for fireLens configuration of type fluentbit. Launch a new task to retry.`

**Expected behavior:**
Task Definition deploys, service starts, logs send to Sumo

**Screenshots**
Side by side of correct and incorrect files.
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/116738048/236857961-03391e7b-1ec8-4c24-8686-e787290166a6.png">

**Desktop/Tablet/Smartphone (please complete the following information):**
 - OS: MacOS
 - Browser chrome

**Additional info:**

**Comment by kimsauce** [comment]
@bethg1 , thank you so much for reporting! I've just fixed the indentation https://script-collection.s3.amazonaws.com/fargate/httpd_fargate_sumologic.json
