### ISSUE TITLE
Align example -- dedup Search Operator

### ISSUE THREAD

**Issue by kostuch-sumologic** [SumoLogic/sumologic-documentation#2495]
**Describe the bug:**
The examples on the dedup Search Operator page don't align.  
There is city data in the Country field. Country data in the Continent field.  

**Expected behavior:**
https://learn.jamf.com/bundle/jamf-protect-documentation/page/Creating_an_Action_Configuration.html

In the Example table:
Create a City field and populate it with cities.  
Populate Country field with countries.
Populate Continent field with continents.  

**Screenshots**

![Screenshot 2023-05-26 at 12 37 13 PM](https://github.com/SumoLogic/sumologic-documentation/assets/106690344/2c887d25-7ec0-46a1-aef4-fc8d726a0010)

**Comment by kimsauce** [comment]
@kostuch-sumologic , great catch! We are super grateful for all of the fixes you've been submitting. Keep them coming🙏
