### ISSUE TITLE
Log Search API search status `DONE GATHERING HISTOGRAM`

### ISSUE THREAD

**Issue by johnduhart** [SumoLogic/sumologic-documentation#2642]
**Provide Feedback on Docs**

The API is returning a job status of `DONE GATHERING HISTOGRAM`, but this isn't documented in the state table.

**Specific page:** https://help.sumologic.com/docs/api/search-job/#get-the-current-search-job-status

**Comment by jpipkin1** [comment]
@johnduhart, thanks for submitting this issue. Sorry it took so long for us to address it.

Here is the pull request with the fix:
https://github.com/SumoLogic/sumologic-documentation/pull/2911

**Comment by jpipkin1** [comment]
@johnduhart, the problem is now fixed:
https://help.sumologic.com/docs/api/search-job/#get-the-current-search-job-status
