### ISSUE TITLE
SDO help link broken

### ISSUE THREAD

**Issue by jd-sumo** [SumoLogic/sumologic-documentation#2814]
**Describe the bug:**
404 on https://help.sumologic.com/Solutions/Software_Development_Optimization_Solution

**Steps to reproduce the behavior:**
1. review [sumologic-sdo-terraform readme ](https://github.com/SumoLogic/sumologic-solution-templates/blob/master/software-development-optimization-terraform/README.md#sumologic-sdo-terraform):

> For more details, Please look at Sumo Logic [Software Development Optimization Help Document](https://help.sumologic.com/Solutions/Software_Development_Optimization_Solution).

2. Follow 'for more details' link ...
 

**Expected behavior:**
Link is valid

**Comment by kimsauce** [comment]
Thanks, @jd-sumo ! Fixing this [here](https://github.com/SumoLogic/sumologic-documentation/pull/2840).

**Comment by jd-sumo** [comment]
Still getting the 404 on
https://help.sumologic.com/Solutions/Software_Development_Optimization_Solution
from the same link.

Do I just need to wait longer ?

--

Jeff Deininger

Architect SE

Sumo Logic

**Comment by kimsauce** [comment]
@jd-sumo It wasn't in effect yet when you commented; PR was in the process of merging. It's fixed now.

**Comment by jd-sumo** [comment]
Thanks all!

--

Jeff Deininger

Architect SE

Sumo Logic
