### ISSUE TITLE
https://help.sumologic.com/docs/dashboards/edit-dashboards/manage-axis/ 404 - Page Not Found 

### ISSUE THREAD

**Issue by roshanchhetri** [SumoLogic/sumologic-documentation#2890]
**Describe the bug:**
Give a clear and concise description of the issue. Include any errors you received.
I googled something and got this link as a result, but this page is not available 
**Steps to reproduce the behavior:**
access this link : https://help.sumologic.com/docs/dashboards/edit-dashboards/manage-axis/ 

**Expected behavior:**
This page should exist
**Screenshots**
![image](https://github.com/SumoLogic/sumologic-documentation/assets/36155840/c7a96507-86b6-42e0-b111-557ec3c45428)

**Desktop/Tablet/Smartphone (please complete the following information):**
 Browser - N/A

**Additional info:**

**Comment by jpipkin1** [comment]
@roshanchhetri, thank you for reporting the problem. The fix will be applied with PR #2896.

**Comment by jpipkin1** [comment]
@roshanchhetri, the issue is now fixed.
