### ISSUE TITLE
Add an example for the Outlier rule "Advanced Expression" field

### ISSUE THREAD

**Issue by jpipkin1** [SumoLogic/sumologic-documentation#2944]
On August 16, 2023, Chas Clawson asked in a direct DM to me and Sourabh Bhosale on Slack:
> Hey guys - Can we get an "Advanced Expression" example added to the outlier rule page. Customers would need to know how to use this field.
> https://help.sumologic.com/docs/cse/rules/write-outlier-rule/

Sourabh Bhosale will provide the example, and I'll add it to the article.

**Comment by jpipkin1** [comment]
Sourabh Bhosale left the company, and didn't provide the example before leaving.

**Comment by jpipkin1** [comment]
@pkazmir-sumo, could you provide us with an "Advanced Expression" example that we could add to the outlier rule article?

https://help.sumologic.com/docs/cse/rules/write-outlier-rule/

**Comment by jpipkin1** [comment]
@pkazmir-sumo responded via email to @jc-sumo:
>Julian, could you help with this please? I’m not the person to ask to write rule expressions.

**Comment by jc-sumo** [comment]
An example where this is used in an OOTB rule is Spike in PowerShell Command Line Length From Host. In this example the rule is looking for outliers in the length of the commandLine. So this uses the MAX aggregation function and `length(commandLine)` to calculate when we see very long commandLines out of the ordinary. I believe syntax for these is the same as the rule expression syntax found here https://help.sumologic.com/docs/cse/rules/cse-rules-syntax/

**Comment by jpipkin1** [comment]
Thanks, @jc-sumo. I'll add something about this to the explanation of the "Advanced Expression" field in the outlier rule article.
