### ISSUE TITLE
Documentation Update: SIGNL4 - Mobile Alerting

### ISSUE THREAD

**Issue by rons4** [SumoLogic/sumologic-documentation#3111]
**Is your feature request related to a problem? Please describe.**
I have seen this documentation here:
https://github.com/SumoLogic/sumologic-documentation/blob/main/docs/integrations/webhooks/signl4.md
(https://help.sumologic.com/docs/integrations/webhooks/signl4/)

**Describe the solution you'd like:**
The above is great. However, I feel for SIGNL4 it would make sense to also add a documentation page under:
https://github.com/SumoLogic/sumologic-documentation/tree/main/docs/alerts/webhook-connections
(https://help.sumologic.com/docs/alerts/webhook-connections/)
There is a description already available here:
https://www.signl4.com/blog/portfolio_item/sumo_logic_mobile_alerting/
The idea is that SIGNL4 is mainly intended to send reliable mobile alerts and it integrates well with Sumo Logic.

**Describe alternatives you have considered:**
If you like we can create the page for the alerting section and I can create a Pull Request for the same.

**Additional info:**
SIGNL4 is a mobile alerting and incident response solution supporting notifications via app push, SMS text, voice calls, including escalation, duty scheduling and collaboration.
I think a listing under the alerting section makes sense.
Just let me know if I can help.

**Comment by jpipkin1** [comment]
@rons4, thank you for submitting this feature request. We'll evaluate it for addition to our documentation set.

**Comment by jpipkin1** [comment]
Related links:
- https://help.sumologic.com/docs/integrations/webhooks/signl4/
- https://help.sumologic.com/docs/alerts/webhook-connections/
- https://www.signl4.com/blog/portfolio_item/sumo_logic_mobile_alerting/
- https://connect.signl4.com/webhook/docs/index.html
- https://www.signl4.com/inbound-webhook-code-snippets/
- https://connect.signl4.com/api/docs/index.html

**Comment by jpipkin1** [comment]
@rons4, I'm sorry for my slow response. You wrote above:
>If you like we can create the page for the alerting section and I can create a Pull Request for the same.

That would be marvelous. When you have the PR ready for review, let me know, and I can review it.

**Comment by rons4** [comment]
Perfect and thank you for your reply. I will create the page and the PR as soon as possible, probable next week.

**Comment by rons4** [comment]
Just created the PR #3142 for this.

**Comment by jpipkin1** [comment]
@rons4, thank you! I'll review the PR today.

**Comment by jpipkin1** [comment]
@rons4, your new article is finally published. I'm sorry about the delay. We've had problems with GitHub the last couple of days:
https://help.sumologic.com/docs/alerts/webhook-connections/signl4/

**Comment by jpipkin1** [comment]
This issue is closed by PR #3145.

**Comment by rons4** [comment]
Thanks a lot @jpipkin1 and @kimsauce for your assistance. Great to see that the page is live now.
