### ISSUE TITLE
Update alert grouping log/metrics text

### ISSUE THREAD

**Issue by kimsauce** [SumoLogic/sumologic-documentation#3294]
This is old way. With alert grouping, this text is not correct anymore. Can you suggest @rmamilla-sumo ?

_Originally posted by @ndhar-sumo in https://github.com/SumoLogic/sumologic-documentation/pull/3291#discussion_r1384073982_

**Comment by jpipkin1** [comment]
Pull request: https://github.com/SumoLogic/sumologic-documentation/pull/4787

**Comment by jpipkin1** [comment]
The article is updated:
https://help.sumologic.com/docs/alerts/monitors/create-monitor/#step-3-notifications-optional
