### ISSUE TITLE
Data Forwarding miscategorized as Data Archiving

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#3338]
**Describe the bug:**
@harrinder [pointed out in the #dochub Slack channel](https://sumologic.slack.com/archives/C0S86TM6K/p1701123183243539) that page is wrongly categorized as Data Archiving, it is actually Data Forwarding. If some review the update history of this page, it can be found that this page was part of Data Forwarding. Couple of months back someone moved it to Data Archiving. https://help.sumologic.com/docs/manage/data-archiving/installed-collectors/

**Comment by jpipkin1** [comment]
The article may have originally been moved and renamed by PR #[2294](https://github.com/SumoLogic/sumologic-documentation/pull/2294)

**Comment by jpipkin1** [comment]
@stacykor, I'll take this ticket, since data forwarding is my area.

**Comment by jpipkin1** [comment]
@JV0812, I'll take this ticket because I'm responsible for [Data Forwarding](https://help.sumologic.com/docs/manage/data-forwarding/) documentation.
