### ISSUE TITLE
doc page feedback

### ISSUE THREAD

**Issue by hoangj-procore** [SumoLogic/sumologic-documentation#3447]
**Provide Feedback on Docs**
Enter feedback for any of the following. If you meant to enter a bug, select Issues then Bug Report. 

For the search job api docs. The section title suggests that you send the post payload with query params but that doesn't work. You need to send the payload with the request body.

**Specific page:**
If you clicked Log an issue through the site, the doc file is in the issue title. Or add a link to the page you want to give feedback on.
https://help.sumologic.com/docs/api/search-job/#query-parameters

**About the site:**
What would you like to see on the website? Section should be corrected to "query request body" or something to that effect as not to confuse the reader with "query params"

**Comment by jpipkin1** [comment]
@hoanj-procore, thank you for your feedback. We'll change "Query parameters" headings to "Request parameters".
