### ISSUE TITLE
Log Level Detection and Insights: Broken elements table

### ISSUE THREAD

**Issue by astencel-sumo** [SumoLogic/sumologic-documentation#3478]
**Describe the bug:**

In the [Log Level and Detection](https://help.sumologic.com/docs/search/get-started-with-search/search-page/log-level/) page, the table under the image with A, B, C, D, E, F elements is broken. The A and B rows of the table are formatted correctly, but the others - C through F - are not treated as a table anymore.

![image](https://github.com/SumoLogic/sumologic-documentation/assets/70892616/ee95a414-c37e-4a90-b78e-2ea9cfd03c2a)

**Desktop/Tablet/Smartphone (please complete the following information):**

 - OS: MacOS 14.2
 - Browsers checked: Firefox, Chrome

**Comment by jpipkin1** [comment]
@astencel-sumo, thank you for reporting the issue. The table is fixed now. It evidently got corrected by doc PR #3482.

**Comment by jpipkin1** [comment]
@astencel-sumo, I spoke too soon. Once we merged doc PR #3486, the problem cropped up again. I'll get it fixed today.
