### ISSUE TITLE
CSS Error on Help Pages

### ISSUE THREAD

**Issue by rollenbuttel** [SumoLogic/sumologic-documentation#3479]
**Describe the bug:**
The help pages are resulting in a CSS error 

**Steps to reproduce the behavior:**
go to any page and you see raw text rather than all the images, fonts and colours that should be loaded in.

If you go to the main page you see this https://help.sumologic.com/

**Comment by jpipkin1** [comment]
@rollenbuttel, thank you for reporting the issue. It was fixed by doc PR #3482.
