### ISSUE TITLE
Log operators documentation points to tutorialspoint

### ISSUE THREAD

**Issue by mfiglus** [SumoLogic/sumologic-documentation#3525]
**Describe the bug:**
[Log operators documentation](https://help.sumologic.com/docs/search/search-cheat-sheets/log-operators/) points to `tutorialspoint` and links don't work

**Steps to reproduce the behavior:**
1. Go to https://help.sumologic.com/docs/search/search-cheat-sheets/log-operators/
2. Click on `split` operator link
3. See error on `tutorialspoint` page

**Expected behavior:**
It should point to sumo docs on the operator

**Screenshots**
<img width="675" alt="Screenshot 2024-01-17 at 10 21 32" src="https://github.com/SumoLogic/sumologic-documentation/assets/56257507/f28a21b6-8bba-47b6-85e5-5e434c346c2c">

**Comment by mgol-sumo** [comment]
Looks like the breakage landed in #3471.

**Comment by mgol-sumo** [comment]
cc @kimsauce
