### ISSUE TITLE
OTLP Source Json config is missing

### ISSUE THREAD

**Issue by Gourav2906** [SumoLogic/sumologic-documentation#3637]
**Describe the bug:**
Give a clear and concise description of the issue. Include any errors you received.

**Steps to reproduce the behavior:**
1. Go to  https://help.sumologic.com/docs/send-data/use-json-configure-sources/
2. OTLP source https://help.sumologic.com/docs/send-data/hosted-collectors/http-source/otlp/ json is missing in 1st pae

**Expected behavior:**
There should be json for otlp source like all other sources

**Screenshots**

**Desktop/Tablet/Smartphone (please complete the following information):**

**Additional info:**

**Comment by jpipkin1** [comment]
@JV0812, I'm assigning this issue to you because you handle our [Send Data](https://help.sumologic.com/docs/send-data/) documentation.

**Comment by JV0812** [comment]
PR related to this issue: https://github.com/SumoLogic/sumologic-documentation/pull/3656

**Comment by JV0812** [comment]
PR related to this issue is merged. So closing this bug.
