### ISSUE TITLE
Unclear wording on SLO page

### ISSUE THREAD

**Issue by mflis-sumo** [SumoLogic/sumologic-documentation#3681]
**Specific page:**

https://help.sumologic.com/docs/observability/reliability-management-slo/

This sentence feels out of sync the image it describes:
> The following chart shows our calculations and an example 5m window for the month of January where a number of requests were unsuccessful due **to a completions that averaged greater than 600ms:**
![image](https://github.com/SumoLogic/sumologic-documentation/assets/124572224/cbbeaded-6109-4010-a32c-b12b260607ae)

AFAIR the image is correct here stating that a time window is marked as bad, because `p99(latency) > 500ms`, as opposed to  `avg(latency) > 500 ms`

**Comment by jpipkin1** [comment]
@kimsauce, since SLO is your area, could you look at this issue?

**Comment by kimsauce** [comment]
> @kimsauce, since SLO is your area, could you look at this issue?

sure thing! thanks for the heads up.

**Comment by jpipkin1** [comment]
Pull request: https://github.com/SumoLogic/sumologic-documentation/pull/4777

**Comment by jpipkin1** [comment]
The documentation is now updated: https://help.sumologic.com/docs/observability/reliability-management-slo/#terminology
