### ISSUE TITLE
404 errors

### ISSUE THREAD

**Issue by skondla** [SumoLogic/sumologic-documentation#394]
**Describe the bug:**
Give a clear and concise description of the issue. Include any errors you received.

**Steps to reproduce the behavior:**
1. Click on '...'
1. Scroll down to '...'
1. See error

**Expected behavior:**
Describe what you expected to happen.

**Screenshots**

**Desktop/Tablet/Smartphone (please complete the following information):**

**Additional info:**

**Comment by kimsauce** [comment]
Hi @skondla , thank you for your interest in contributing! I'm only seeing the template in your submission - was there something specific you'd like to report?

**Comment by kimsauce** [comment]
@skondla , I'm going to close this out. If there's anything we can help you with, let us know.
