### ISSUE TITLE
Update File Path in opentelemetry-collector/data-source-configurations/collect-logs/ Document

### ISSUE THREAD

**Issue by CowpD** [SumoLogic/sumologic-documentation#4319]
https://help.sumologic.com/docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs/

File Path in configuration steps says to place .yaml file in "config" folder:
"1. Create a file in folder C:\ProgramData\Sumo Logic\OpenTelemetry Collector\config\ with name sysmon_windows.yaml."

Suggest correct path should be "C:\ProgramData\Sumo Logic\OpenTelemetry Collector\config\conf.d" as stated in the OpenTelemetry configuration yaml itself:
"## All modifications should be put as separate files in conf.d subdirectory"

In my testing, moving the sysmon_windows.yaml from "/config" and into "/config/conf.d" without any other configuration changes made, was the difference between OpenTelemetry correctly forwarding Sysmon logs, and not.

**Comment by jpipkin1** [comment]
@CowpD, I'll work this issue with our internal Jira ticket: https://sumologic.atlassian.net/browse/DOCS-340.

**Comment by jpipkin1** [comment]
@CowpD, the file path is now fixed: https://help.sumologic.com/docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs/#collect-from-custom-channels-powershell-sysmon
