### ISSUE TITLE
Minor Edit on Threat and Detection

### ISSUE THREAD

**Issue by canntankrus** [SumoLogic/sumologic-documentation#4399]
Great page...

The parenthetical note on Step 3 under Step 7: Look up user information with CrowdStrike does not apply.  Looks like it was copied from the previous example.

https://help.sumologic.com/docs/security/additional-security-features/threat-detection-and-investigation/#step-7-look-up-user-information-with-crowdstrike

**Comment by jpipkin1** [comment]
@canntankrus, thank you for letting us know about the error. We'll fix it.

**Comment by jpipkin1** [comment]
Pull request: https://github.com/SumoLogic/sumologic-documentation/pull/4401

**Comment by jpipkin1** [comment]
@canntankrus, it's fixed now. Let us know if you find anything else.
