### ISSUE TITLE
IIS 10 OpenTelemetry Collector yaml bug

### ISSUE THREAD

**Issue by Daren-rpi** [SumoLogic/sumologic-documentation#4867]
**Describe the bug:**
The IIS 10 OpenTelemetry Collector app generates an incorrect yaml file by default.

**Steps to reproduce the behavior:**
1. Go to 'IIS 10 - OpenTelemetry Application'
1. Follow instructions to generate config yaml

The otel logs pipeline processor is generated as follows in the output yaml:

      processors:
        - memory_limiter
        - resource/iis_resource_attributes/[GUID]
        - resourcedetection/system

But the resource/iis_resource_attributes/[GUID] processor references the hostname attribute that is added in resourcedetection/system, which does not exist because the ordering is wrong.  This section should be generated as:

      processors:
        - memory_limiter
        - resourcedetection/system
        - resource/iis_resource_attributes/[GUID]

**Expected behavior:**
Logs load into Sumo and IIS dashboards work.

**Screenshots**

**Desktop/Tablet/Smartphone (please complete the following information):**

**Additional info:**

**Comment by jpipkin1** [comment]
@JV0812, this issue is not a documentation problem, and should be assigned to someone in development. Since you are in contact with the apps and source developers, could you assign this to the appropriate person?

**Comment by JV0812** [comment]
Sure @jpipkin1.
@npande @himanshu219 Can you guys take a look at this PR and let us know if we need any docs change later. Thanks!

**Comment by sumoanema** [comment]
The issue has been fixed and deployed in the latest version 1.0.8

**Comment by jpipkin1** [comment]
Thank you, @sumoanema. Closing this ticket.
