### ISSUE TITLE
Fix formatting in CSE doc table

### ISSUE THREAD

**Issue by kimsauce** [SumoLogic/sumologic-documentation#498]
For the *Quick reference to configuring ingest mappings* section, the table is not formatted and just shows plain text. <https://help.sumologic.com/docs/cse/ingestion/sumo-logic-ingest-mapping/#quick-reference-to-configuring-ingest-mappings>

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1665100800513479)

**Comment by MariePMcGarry** [comment]
table is fixed: https://help.sumologic.com/docs/cse/ingestion/sumo-logic-ingest-mapping/#quick-reference-to-configuring-ingest-mappings
