### ISSUE TITLE
Kafka logo difficult to see in Dark mode

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#573]
Kafka logo difficult to see in Darkmode
/docs/integrations/containers-orchestration/kafka
![Screen Shot 2022-10-10 at 11 59 07 AM](https://user-images.githubusercontent.com/4722362/194935466-fe082729-3722-4f4b-98bd-2b0dc9c9f537.png)

**Comment by kimsauce** [comment]
Fixed https://github.com/SumoLogic/sumologic-documentation/pull/579
