### ISSUE TITLE
mimecast no sidebar

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#574]
Mimecast 
![Screen Shot 2022-10-10 at 10 49 12 AM](https://user-images.githubusercontent.com/4722362/194940119-534c6531-f3c1-4277-ba5b-94c71c05b4cf.png)

**Comment by kimsauce** [comment]
Fixed https://help.sumologic.com/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/mimecast-source/
