### ISSUE TITLE
Update AWS Cloudformation docs to reflect v2.5.1

### ISSUE THREAD

**Issue by kimsauce** [SumoLogic/sumologic-documentation#582]
The latest deployment of AWSO is 2.5.1, new docs provide links to 2.5.0 template instead of 2.5.1 template. The latest version is essential since there are parts to the old template that are no longer going to be supported by AWS. <https://help-opensource.sumologic.com/docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation>

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1664822865717389)

**Comment by kimsauce** [comment]
@nmohantyctr , if the PR is merged, can you please close?

**Comment by nmohantyctr** [comment]
It's updated and published.
