### ISSUE TITLE
Image expander is buggy

### ISSUE THREAD

**Issue by kimsauce** [SumoLogic/sumologic-documentation#584]
- In light mode, images are not really clear when expanded
- When expanding images, they sometimes do not magnify properly and/or freeze
- Takes two clicks to get it to unexpand/minimize.
- When you click on the images in the page to zoom in they are greyed out, then I click away and the image is now in full bright zoomed in and the background is fully visible
- Is it possible to disable expansion for some images like [icons](https://drive.google.com/file/d/1L1I3_IZJhWxl4oTeMKYplofQn_MI_tzM/view)?

**Comment by kimsauce** [comment]
@SumoLogic/open-source-collection-team , could we work with you on troubleshooting this?

**Comment by stacykor** [comment]
@swiatekm-sumo is this something you can help with or do we need to turn to the web team?

**Comment by jpipkin1** [comment]
Original Slack message: https://sumologic.slack.com/archives/C0S86TM6K/p1664446694720709

**Comment by jpipkin1** [comment]
@kimsauce, I have no idea what "image expander" is. The images in our docs seem to work fine. So I'm closing this ticket. Reopen it and assign it to me if you disagree.

**Comment by kimsauce** [comment]
Thank you, @jpipkin1 ! This is a feature that allows you to click and expand images. It never worked correctly. Ok to close.
