### ISSUE TITLE
fix code formatting

### ISSUE THREAD

**Issue by MariePMcGarry** [SumoLogic/sumologic-documentation#612]
<@U4HKQNM2Q>  This page shows Search code as one line whereas it should show up as separate line after very pipe
<https://help.sumologic.com/docs/search/get-started-with-search/build-search/best-practices-search/>

Put pipe-delimited operations on separate lines
For readability, use a soft return in the query field to put each new pipe-delimited operation on a separate line.
Best approach:
```_sourceCategory=Apache/Access and GET | parse "\"GET * HTTP/1.1\"\" * * \"\"*\"\"" as url,status_code,size,referrer | count by status_code,referrer | sort _count```

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1665515100933049?thread_ts=1665515100.933049&cid=C0S86TM6K)

**Comment by MariePMcGarry** [comment]
fixed in source

**Comment by kimsauce** [comment]
> fixed in source

hi @MariePMcGarry , if you've fixed it, you can close out the ticket below
