### ISSUE TITLE
Redirect for Deploy/Configure App Components Solution

### ISSUE THREAD

**Issue by nmohantyctr** [SumoLogic/sumologic-documentation#634]
**Describe the bug:**
Give a clear and concise description of the issue. Include any errors you received.

**Steps to reproduce the behavior:**
1. Go to 'https://help.sumologic.com/Observability_Solution/Application_Component_Solution/Deploy_and_Configure_Application_Components_Solution'

**Expected behavior:**
It needs to redirect to: https://help.sumologic.com/docs/observability/app-components/

**Screenshots**

**Desktop/Tablet/Smartphone (please complete the following information):**

**Additional info:**

**Comment by kimsauce** [comment]
fixed
