### ISSUE TITLE
Cloud Syslog search

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#647]
Not sure how the doc search results are ranked exactly, but thought I'd point this out as an example.
Cloud Syslog has it's own page but doesn't pop up in the first few pages of search results.
<https://help.sumologic.com/docs/send-data/hosted-collectors/Cloud-Syslog-Source>

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1665669496579989)

**Comment by kimsauce** [comment]
fixed
