### ISSUE TITLE
SOAR should be Cloud SOAR on main page

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#667]
**Describe the bug:**
Give a clear and concise description of the issue. Include any errors you received.

**Steps to reproduce the behavior:**
1. Go to Home
1. Click on Security and Incidents
1. Scroll down to SOAR
1. See error, should be Cloud SOAR

**Expected behavior:**
Describe what you expected to happen.

**Screenshots**

**Desktop/Tablet/Smartphone (please complete the following information):**

**Additional info:**

**Comment by kimsauce** [comment]
fixed!
