### ISSUE TITLE
num operator / floating point number

### ISSUE THREAD

**Issue by kimsauce** [SumoLogic/sumologic-documentation#690]
The [`num` operator](https://help.sumologic.com/docs/search/search-query-language/search-operators/num/) doc states:

"... num operator converts a field to a floating point number."

But I can't find reference to "float". I am only familiar w/ (looking at the lookup creation screen), `boolean`, `int`, `long`, `double`, `string`  datatypes. Which is the one that `num` returns?

Whatever type that is, maybe we can make that sentence read as follows
&gt; "... num operator converts a field to a &lt;correct_data_type&gt;."

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1666036821777319)

**Comment by stacykor** [comment]
Not a bug. Do you have the original request. It's a floating point number. It converts to a number with a decimal provided the value of the field is a negative/positive integer or a real number.

**Comment by stacykor** [comment]
https://www.freecodecamp.org/news/floating-point-definition/#:~:text=A%20floating%20point%20number%2C%20is,float%22%20to%20any%20position%20necessary.

**Comment by kimsauce** [comment]
@stacykor if you click "Slack message" (bottom of each Issue description), it takes you to the original request

**Comment by stacykor** [comment]
Thanks for the tip, but still waiting on Manas (PM) to verify there's no better descriptor.

**Comment by kimsauce** [comment]
Followed up w/Manas/Stacy via Slack
