### ISSUE TITLE
Custom Log Formats for Traffic and Threat are swapped - Palo Alto

### ISSUE THREAD

**Issue by wjakelee** [SumoLogic/sumologic-documentation#712]
**Describe the bug:**
The Custom Log Formats for Traffic and Threat are swapped. Also recommend removing the # from the token in the log format as it is not needed and confuses customers.

**Steps to reproduce the behavior:**
https://help.sumologic.com/docs/integrations/cloud-security-monitoring-analytics/palo-alto-firewall-10/#step-2-define-the-destination-for-the-logs
scroll to custom log formats

**Screenshots**
![image](https://user-images.githubusercontent.com/60631110/196818630-29156709-9e28-4643-95c6-50932f177875.png)

**Desktop/Tablet/Smartphone (please complete the following information):**
 - OS: iOS
 - Browser chrome
Version 106.0.5249.119

**Comment by JainM6** [comment]
@wjakelee 
I don't see the **#** here https://help.sumologic.com/docs/integrations/cloud-security-monitoring-analytics/palo-alto-firewall-10/, and the log formats screenshots are not matching either.
Please check the screenshot below:
[Screenshot.
<img width="1151" alt="Screen Shot 1401-08-12 at 01 02 23" src="https://user-images.githubusercontent.com/116072777/199586121-2359452c-37c8-4b3f-8646-2e6f6d683d27.png">

Could you please check and confirm which one is correct and what needs to be changed?

**Comment by kimsauce** [comment]
@wjakelee fixed in separate PR
