### ISSUE TITLE
Finish migrating AWS EC2 and Host Metrics Observability apps

### ISSUE THREAD

**Issue by MariePMcGarry** [SumoLogic/sumologic-documentation#717]
*`AWSO docs needs fixes`*
Need to ensure the content on opensource page is in sync with helpstaging
<https://helpstaging.sumologic.com/Observability_Solution/AWS_Observability_Solution/AWS_Observability_Apps>
<https://help-opensource.sumologic.com/docs/observability/aws/integrations/>

The helpstaging page contains two options for EC2 related apps. This is not synced with what we are currently showing on new page
What's shown on helpstaging
• Host Metrics (EC2)
• AWS EC2
What's Covered on new page (not proper)
• AWS EC2 Metrics

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1666242741125119)

**Comment by stacykor** [comment]
@nmohantyctr this is something we expected to have done by launch. Can you confirm your progress?

**Comment by kimsauce** [comment]
@JainM6 , since this migration check was assigned to you, I've assigned this Issue to you. Would you kindly follow up with the requester to confirm everything is up to date?

**Comment by nmohantyctr** [comment]
The Host Metrics link is present in the Doc as AWS EC2 Host Metrics.

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/100399068/205229377-7c54e415-b86e-4d1b-a0f3-a9303cb29df8.png">
