### ISSUE TITLE
custom log format

### ISSUE THREAD

**Issue by MariePMcGarry** [SumoLogic/sumologic-documentation#727]
<@U4HKQNM2Q> Here is the follow-up query from the customer.

&gt; Well, I couldn’t find any description about “Custom Log Format” in the github.
&gt; Originally, we should be able to copy the Custom Log Format in your article and past it to PaloAlto.
&gt; But currently we can’t do it.
&gt; Don’t you fix your article?
&gt; If you won’t fix it, I’ll request the customer to refer the github and configure the Custom Log Format by themselves.

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1666320904725529?thread_ts=1665649123.508899&cid=C0S86TM6K)

**Comment by kimsauce** [comment]
Per @mvirga01 , this is complete
