### ISSUE TITLE
Update Collecting Logs for CrowdStrike App

### ISSUE THREAD

**Issue by MariePMcGarry** [SumoLogic/sumologic-documentation#739]
Duc Ha
 Today at 6:29 AM
Hi Team, could someone update this page: https://help.sumologic.com/docs/integrations/security-threat-detection/crowdstrike-falcon-endpoint-protection/. Specifically the “Collecting Logs for the CrowdStrike App” section, the Caution part. We have the same C2C source for FedRamp now (https://help.sumologic.com/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/CrowdStrike-Source/)  so don’t need to use the Legacy Falcon SIEM connector based legacy method (edited) 

Duc Ha
  1 hour ago
Also in the doc for the C2C source (https://help.sumologic.com/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/CrowdStrike-Source/),
1) remove “Use the legacy collection method for CrowdStrike.” from the Note. and
2) “Forward to SIEM” values are wrong. Should be:
_siemVendor = CrowdStrike
_siemProduct = Falcon Endpoint Protection (CNC)
_siemFormat = JSON
_siemEventID = {metadata.eventype} where metadata.eventtype is populated from the field in the event JSON, ie (IncidentSummaryEvent or DetectionSummaryEvent )

**Comment by nmohantyctr** [comment]
The [doc](https://help.sumologic.com/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/CrowdStrike-Source/#create-acrowdstrikesource) is updated.
