### ISSUE TITLE
Mapper documentation confusing text

### ISSUE THREAD

**Issue by kostuch-sumologic** [SumoLogic/sumologic-documentation#767]
Under the **Mapper** section of **Parsing Language Reference Guide** (https://help.sumologic.com/docs/cse/schema/parsing-language-reference-guide/#mapper).  This paragraph is confusing and the second sentence is not clear.
Specify the product, vendor, and event_id for the message. If you identify the mapper using , all three are required: you’ll define three MAPPER attributes. Templating is allowed for each value. However, the most common and best practice is to define vendor and product using static strings. event_id often varies based on the log type so it’s more common to use templating when defining that.

https://user-images.githubusercontent.com/106690344/198131927-4573df76-568e-4e36-ba4e-9580a04e00e1.png

**Comment by stacykor** [comment]
@MariePMcGarry I believe this one is yours.

**Comment by MariePMcGarry** [comment]
I have checked in an update to clarify https://help.sumologic.com/docs/cse/schema/parsing-language-reference-guide/#mapper. It won't appear on site til https://github.com/SumoLogic/sumologic-documentation/pull/1093 is merged.
