### ISSUE TITLE
Customer Feedback on observability and metrics links

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#795]
Hello! Sharing feedback directly from our customer:

Regarding the Sumo Logic documentation, there are things that could be improved. For instance, 

1. it is [said that monitors have a mute state](https://help.sumologic.com/docs/alerts/monitors/terminology), but no further information about this is given. 
1. The [tf provider docs](https://registry.terraform.io/providers/SumoLogic/sumologic/latest/docs/resources/monitor) have great examples, though some of the links lead to 404, like on [this page about SLOs](https://registry.terraform.io/providers/SumoLogic/sumologic/latest/docs/resources/slo). 
1. And after [reading the docs](https://help.sumologic.com/docs/observability/aws/) a few times, I'm still not sure what "AWS Observability" means vs. just using the logs and metrics collected using the collector.

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1666960876273379)

**Comment by stacykor** [comment]
Adding Kim as there's Observability feedback here. And @MariePMcGarry for Metrics.

**Comment by kimsauce** [comment]
I will break this up into separate Issues. For issue 1, we're about to release a feature about muting monitors/alerts, so updates are on the way. For issue 2, [did the fix](https://github.com/SumoLogic/sumologic-documentation/pull/1359). For issue 3, will create a separate ticket.
