### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#840]
We have a broken link for the insight server on this page <https://help.sumologic.com/docs/cse/integrations/insight-enrichment-server/> it takes you to <https://https//script-collection.s3.amazonaws.com/caravel/windows-enrichment-server-installer.exe> we just need to drop the https//

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1667476767959779)

**Comment by kimsauce** [comment]
this one is fixed
