### ISSUE TITLE
Remove Beta Label from Infrequent Tiers

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#841]
Can we please take down this page, it is no longer in beta: <https://help.sumologic.com/docs/manage/partitions-data-tiers/infrequent-tier-search/>. cc:  <@U03FB71KE76> <@U016Y89KT09>

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1667488380250689)

**Comment by stacykor** [comment]
https://github.com/SumoLogic/sumologic-documentation/pull/847

**Comment by kimsauce** [comment]
Closing this one as it's a duplicate (see https://github.com/SumoLogic/sumologic-documentation/issues/846)
