### ISSUE TITLE
Remove Beta label from Infrequent Tier Support

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#846]
Can we please take down this page, it is no longer in beta: <https://help.sumologic.com/docs/manage/partitions-data-tiers/infrequent-tier-search/>. cc:  <@U03FB71KE76> <@U016Y89KT09>

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1667488380250689)

**Comment by MariePMcGarry** [comment]
removed page, and removed entry from sidebar.

**Comment by kimsauce** [comment]
This is done. Spoke with Manas on April 30 about Infrequent Tier beta and similar features and he confirmed this and all related docs are up to date.
