### ISSUE TITLE
Update Connections Redirects

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#884]
Hey folks, I'm seeing a 404 when hitting: <https://help.sumologic.com/Manage/Connections_and_Integrations>.  That's coming from here: <https://www.sumologic.com/application/heroku/>.

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1667920771403969)

**Comment by kimsauce** [comment]
Closing - Stacy completed
