### ISSUE TITLE
missinsg links in g suite alert center ingestion doc

### ISSUE THREAD

**Issue by MariePMcGarry** [SumoLogic/sumologic-documentation#885]
Hi team,

Looks like we’re missing two links in <https://help.sumologic.com/docs/cse/ingestion/g-suite-alert-center/#step-2-configure-g-suite-alert-center>. Can we please fix?

The corresponding page from the old documentation is here: <https://helpstaging.sumologic.com/Cloud_SIEM_Enterprise/CSE_Ingestion/G_Suite_Alert_Center#step-2-configure-g-suite-alert-center>

And the two missing links are here:
<https://helpstaging.sumologic.com/07Sumo-Logic-Apps/06Google/Google_Workspace/01Collect-Logs-for-Google-Workspace/02Configure_Collection_for_Google_Workspace_Alert_Center/Configure_Google_Cloud_Platform_Collection_for_Google_Workspace_Alert_Center>

<https://helpstaging.sumologic.com/07Sumo-Logic-Apps/06Google/Google_Workspace/01Collect-Logs-for-Google-Workspace/02Configure_Collection_for_Google_Workspace_Alert_Center/Configure_Script-Based_Collection_for_Google_Workspace_Alert_Center>

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1667923565649379)

**Comment by MariePMcGarry** [comment]
@duchatran This section: https://help.sumologic.com/docs/cse/ingestion/g-suite-alert-center/#step-2-configure-g-suite-alert-center, has missing links for the two methods of configuring G Suite Alert Center to send logs to Sumo Logic:

- Google Cloud Platform (GCP) collection
- Script-based collection

1. Should  the **Google Cloud Platform (GCP) collection** link point to: https://help.sumologic.com/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source?

2. What topic  should **Script-based collection** point to?

**Comment by MariePMcGarry** [comment]
@duchatran This is the latest one I pinged you on. Thanks.

**Comment by MariePMcGarry** [comment]
@duchatran said to ask in #sbu-cse-connectors-internal. Posted request for help there.

**Comment by duchatran** [comment]
We don't need the whole Section on Step 2 - that was for a legacy method (with 2 options: either via a customer-hosted Google Function or a self-hosted script).

**Comment by MariePMcGarry** [comment]
Updated https://help.sumologic.com/docs/cse/ingestion/g-suite-alert-center/
