### ISSUE TITLE
Customer inquiry: Does Sumo support Logentries (logentries.com)?

### ISSUE THREAD

**Issue by ram62836** [SumoLogic/sumologic-documentation#905]
Is there a way to import logs from Logentries into sumologic?

**Comment by kimsauce** [comment]
Hi @ram62836 , thanks for reaching out! What type of data source are you using?

**Comment by kimsauce** [comment]
Hi @ram62836 , thank you for reaching out! Let me check with our Apps team, and I'll write you back here.

**Comment by ram62836** [comment]
> Hi @ram62836 , thank you for reaching out! Let me check with our Apps team, and I'll write you back here.

Thanks @kimsauce

**Comment by kimsauce** [comment]
Hi @ram62836 , thank you for your patience. Although we won't have a supported Logentries app at the moment, you can export your data from Logentries and import into Sumo:

- https://logentries.com/product/api-integrations/
- https://github.com/rapid7/leexportpy

Sumo accepts anything you can get into an ascii format and point at an http_endpoint.

For further guidance, please open a support ticket here: https://support.sumologic.com.
