### ISSUE TITLE
Azure Active Directory App - broken script links

### ISSUE THREAD

**Issue by MariePMcGarry** [SumoLogic/sumologic-documentation#909]
Hi docs team,

I have a customer reporting three broken `ps1` links in <https://help.sumologic.com/docs/integrations/microsoft-azure/active-directory-legacy/#b-download-and-deploy-sumo-scripts>. Those same three links in <https://helpstaging.sumologic.com/07Sumo-Logic-Apps/04Microsoft-and-Azure/Active_Directory_Legacy/Collect_Log_Files_for_the_Active_Directory_Legacy_App#b-download%C2%A0and-deploy-sumo%C2%A0scripts|https://helpstaging.sumologic.com/07Sumo-Logic-Apps/04Microsoft-and-Azure/Active_Director[…]cy/Collect_Log_Files_for_the_Active_Directory_Legacy_App> works. Can you please fix?

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1668006532019609?thread_ts=1668006532.019609&cid=C0S86TM6K)

**Comment by kimsauce** [comment]
@nmohantyctr , can you please handle this one as it's apps-related?

**Comment by nmohantyctr** [comment]
The links are updated under PR: https://github.com/SumoLogic/sumologic-documentation/pull/1137
