### ISSUE TITLE
Missing Metadata Fields

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#932]
Team, we need to highlight the *"Metadata fields"* related content across our whole documentation (Example shown in 1.Highlighted_text), as this can very easily missed by any customer/user. These fields are very important for a lot of our OOTB dashboards to work. If these metadata fields are missed during the configuration of any said app in the App Catalog, the dashboards will end up getting created but there will be no data in them. We need to add the information about "Metadata fields" in a separate note and highlight them, so that any customer/user doesn't miss this. *This could also affect other apps in our App Catalog where metadata fields are required.*   I've added one such example of this below with screenshots.
<@U56GPKHDX> <@U6AN2BPHU> <@UNXGHKH2L>
*Example:*
*Installing the AWS EC2 Host metrics app:*
The doc link below:
<https://help.sumologic.com/docs/integrations/amazon-aws/ec2-host-metrics/>
Pictures 2 and 3 show that when there are no metadata fields added , dashboards are created but no data in them.
Pictures 4 and 5 show that when metadata fields are added, dashboards are created and data comes through.

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1668184733783689?thread_ts=1668184733.783689&cid=C0S86TM6K)

**Comment by stacykor** [comment]
@nmohantyctr what is the status of this?

**Comment by nmohantyctr** [comment]
The issue has already been resolved. The same is confirmed in the slack thread.
