### ISSUE TITLE
Unable to search the topics "s3-event-notifications-integration"

### ISSUE THREAD

**Issue by JainM6** [SumoLogic/sumologic-documentation#957]
This search in docs isn’t working but we do have a doc for it.
S3 Event Notifications Integration
<https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-s3-source/#s3-event-notifications-integration>

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1668552729908099)

**Comment by kimsauce** [comment]
fixed in ss360
