### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#960]
broken link - <https://help.sumologic.com/Solutions/Atlassian_Solution/Introducing_the_Atlassian_Solution>

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1668636862030619)

**Comment by kimsauce** [comment]
Hi @stacykor , I checked the legacy docs and this doesn't exist. I've let the requester know and asked where she got it. May need to redirect to our Jira / Jira Cloud solutions instead.

**Comment by stacykor** [comment]
It existed and was obsoleted.

**Comment by stacykor** [comment]
Lisa pointed out to the old link on the corporate site. Kim followed up with them
