### ISSUE TITLE
Error in CSE Insight Enrichment Server doc

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#984]
Hello Doc team, the description for the URL setting on this page is wrong <https://help.sumologic.com/docs/cse/integrations/insight-enrichment-server/#general-settings>.

It currently says:
```The URL of your CSE portal, for example, <https://XXXX.sumologic.com>```
This is not correct, the value needed here is not the URL of the CSE portal but the API endpoint of their deployment. Just had a customer run into this and it was fixed by entering the API endpoint.

On that same description, you can direct customer to our endpoints doc at <https://help.sumologic.com/docs/api/getting-started/>.

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1668804776993019)

**Comment by MariePMcGarry** [comment]
fixed in https://github.com/SumoLogic/sumologic-documentation/pull/1124
