### ISSUE TITLE
Pager Duty missing graphic

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#985]
Team, Noticed some unrelated wording on the '*Configure a Sumo Logic Collector and Source'*  section in the Pagerduty-V3 page . Looking at the wording , I suspect a .png file is missing there. Highlighted Screenshot and doc link below:
Doc link: <https://help.sumologic.com/docs/integrations/saas-cloud/pagerduty-v3/#configure-a-sumo-logic-collector-and-source>

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1668803482922269)

**Comment by stacykor** [comment]
@nmohantyctr What is the status on this?

**Comment by nmohantyctr** [comment]
Closing this PR as corrected Doc under: https://github.com/SumoLogic/sumologic-documentation/pull/1100
