### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by JainM6** [SumoLogic/sumologic-documentation#989]
This URL shows: `404 - Page Not Found.`   <https://help.sumologic.com/07Sumo-Logic-Apps/10Containers_and_Orchestration/Docker_Apps/Docker_ULM/Collect_Logs_and_Metrics_for_Docker_ULM>. how ever this works from helpstaging : <https://helpstaging.sumologic.com/07Sumo-Logic-Apps/10Containers_and_Orchestration/Docker_Apps/Docker_ULM/Collect_Logs_and_Metrics_for_Docker_ULM>

[Slack Message](https://sumologic.slack.com/archives/C0S86TM6K/p1668639281253609)

**Comment by nmohantyctr** [comment]
https://help.sumologic.com/07Sumo-Logic-Apps/10Containers_and_Orchestration/Docker_Apps/Docker_ULM/Collect_Logs_and_Metrics_for_Docker_ULM now redirects to https://help.sumologic.com/docs/integrations/containers-orchestration/docker-ulm/
